openapi: 3.0.3
info:
  title: SymptomSync reminder api Spec
  version: 1.0.0
paths:
  /reminder/api:
    get:
      summary: List reminder api resources
      responses:
        '200':
          description: Successful response
    post:
      summary: Create reminder api resource
      responses:
        '201':
          description: Created
